---
title: "DE_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# This script takes as input data derived from a number of original physical samples, 
# each subjected to three treatments: 1) RNA-seq after poly-A-enrichment, 2) RNA-seq 
# after ribo-depletion, 3) data from ribo-depletion downsampled to produce 
# pseudo-poly-A-enriched samples. The script performs differential expression analysis 
# and plots the results in the form of the first two components in a PCA.
#
# Requires:
#   1) an Excel file with the following columns (with headers; see line 49):
#      i) 'gsm': the identifier for that sample and library prep method
#      ii) 'library_method': the method used for library preparation, including
#          downsampling if appropriate
#      iii) 'pair': an integer denoting which samples were drawn from the same
#           original physical sample
#
#   2) a folder (see line 59) containing the salmon output files from the snakemake 
#      pipeline ('Snakefile_pt2'). The file names should be the gsm names from the
#      Excel file above, followed by "_quant.sf".
#
# Outputs:
#   1) The primary output is a PCA plot for visualizing the similarities and 
#      differences among samples and library prep methods.The output files generated by
#      DESeq2 may, of course, be examined for more details.
```


```{r code}
library(biomaRt)
ensembl=useMart("ensembl", dataset = "hsapiens_gene_ensembl")
att = listAttributes(ensembl)
g <- getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id"), mart = ensembl)

library(tximport)
library(readr)
library(tximportData)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(DESeq2)
library (ggplot2)
library(tidyverse)
library(readxl)
dir <- system.file("extdata", package="tximportData")

gsms = 'orig_samples_with_ds.xlsx'
samples <- read_excel(gsms, col_types = c("text","text","text")) 
samples %>%
  mutate (pair <- as.factor(pair))
rownames(samples) <- samples$gsm
gsm <- samples$gsm

k <- keys(TxDb.Hsapiens.UCSC.hg38.knownGene, keytype="TXNAME")
tx2gene <- g
f <- paste(gsm,"_quant.sf", sep = "")
files <- file.path(getwd(),"diff_expr_data",f)
names(files) <- gsm
txi <- tximport(files, type="salmon", tx2gene=tx2gene[complete.cases(tx2gene), ], 
                ignoreAfterBar = TRUE, ignoreTxVersion = TRUE)
ddsTxi <- DESeqDataSetFromTximport(txi, colData = samples, design = ~ pair + library_method)
rld <- rlog(ddsTxi, blind = FALSE)

pcaData <- plotPCA(rld, intgroup=c("gsm"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=samples$pair, shape = samples$library_method)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) +
  labs(color = "matched pair") +
  labs(shape = "library method") + 
  scale_shape_discrete (labels = c("after downsampling", "polyA", "ribo")) +
  coord_fixed()
```
